# Generated by Django 3.2.9 on 2021-11-15 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=120, verbose_name='نام کامل')),
                ('age', models.IntegerField(null=True, verbose_name='سن')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='شهر')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='تلفن')),
                ('degree', models.IntegerField(blank=True, choices=[(0, 'عمومی'), (1, 'تخصص'), (2, 'فوق تخصص')], null=True, verbose_name='درجه تحصیلی')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='عنوان دکتر')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
        ),
    ]
