# Generated by Django 3.2.9 on 2021-11-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ساخت حساب دکتر', 'verbose_name_plural': 'ساخت حساب دکتر'},
        ),
    ]
