# Generated by Django 3.2.9 on 2021-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'منشی (سطح 0)'), (1, 'دکتر (سطح 1)'), (2, 'ادمین سیستم (سطح 3)')], default=0, null=True, verbose_name='سطح دسترسی'),
        ),
    ]
