# Generated by Django 3.2.9 on 2021-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'منشی (سطح 0)'), (1, 'دکتر (سطح 1)'), (2, 'ادمین سیستم (سطح 3)')], default=0, null=True),
        ),
    ]
