# Generated by Django 3.2.9 on 2021-11-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان مراجعه'),
        ),
    ]
