# Generated by Django 3.2.9 on 2021-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_alter_visit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DateTimeField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
